[envs.default]
python = "3.11"
dependencies = [
    "numpy>=2.2.2",
    "python-dotenv>=1.0.0",
    "qiskit>=1.3",
    "qiskit-aer>=0.15.0",
    "qiskit-ibm-runtime>=0.34.0",
    "ortools>=9.11",
    "matplotlib>=3.10.0",
    "plotly>=6.0.0",
]
type = "virtual"
compile-dependencies = true

[envs.lint]
dependencies = [
  "black==25.1.0",
  "ruff==0.9.4",
  "mypy==1.14.1",
]
type = "virtual"
compile-dependencies = true

[build.targets.wheel]
packages = ["src/qcongen"] 